# Databricks notebook source
# MAGIC %md
# MAGIC # Apply Metadata — descriptions + tags on every demo table
# MAGIC
# MAGIC One-shot, idempotent pass over the radar-databricks schemas:
# MAGIC - **Schema** comments
# MAGIC - **Table** comments for the 6 demo tables + the radar audit log
# MAGIC - **Column** comments for high-traffic tables (input/output to Radar,
# MAGIC   the gold concentration, the scenario results)
# MAGIC - **UC tags** for governance (data_classification, business_unit,
# MAGIC   domain, demo)
# MAGIC
# MAGIC Safe to re-run — every statement is guarded. Missing tables are
# MAGIC skipped, never break the run.

# COMMAND ----------

dbutils.widgets.text("catalog_name",  "radar_databricks_demo")
dbutils.widgets.text("bronze_schema", "bronze")
dbutils.widgets.text("silver_schema", "silver")
dbutils.widgets.text("gold_schema",   "gold")

catalog = dbutils.widgets.get("catalog_name")
bronze  = dbutils.widgets.get("bronze_schema")
silver  = dbutils.widgets.get("silver_schema")
gold    = dbutils.widgets.get("gold_schema")

# COMMAND ----------

def _esc(s: str) -> str:
    return (s or "").replace("'", "''")


def _table_exists(fqn: str) -> bool:
    try:
        spark.table(fqn).schema
        return True
    except Exception:
        return False


def _set_table_comment(fqn: str, comment: str) -> None:
    if not _table_exists(fqn):
        print(f"  [skip] {fqn} does not exist")
        return
    try:
        spark.sql(f"COMMENT ON TABLE {fqn} IS '{_esc(comment)}'")
        print(f"  ✓ {fqn}")
    except Exception as e:
        print(f"  [err] {fqn}: {str(e)[:120]}")


def _set_column_comments(fqn: str, col_comments: dict) -> None:
    if not _table_exists(fqn):
        return
    existing = {c.name for c in spark.table(fqn).schema.fields}
    for col, comment in col_comments.items():
        if col not in existing:
            continue
        try:
            spark.sql(f"ALTER TABLE {fqn} ALTER COLUMN {col} COMMENT '{_esc(comment)}'")
        except Exception as e:
            print(f"  [err] {fqn}.{col}: {str(e)[:80]}")


def _set_table_tags(fqn: str, tags: dict) -> None:
    if not _table_exists(fqn):
        return
    pairs = ", ".join(f"'{k}' = '{_esc(v)}'" for k, v in tags.items())
    try:
        spark.sql(f"ALTER TABLE {fqn} SET TAGS ({pairs})")
    except Exception as e:
        print(f"  [warn] tags on {fqn}: {str(e)[:80]}")


# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Schema comments

# COMMAND ----------

SCHEMA_COMMENTS = {
    bronze: "radar-databricks demo — bronze landing zone. Two synthetic raw "
            "tables: property_book (50K UK home-insurance policies) and "
            "flood_overlay (~150 postcode districts with synthetic flood scores). "
            "All values are demo-grade — no real ABI / EA data is used.",
    silver: "radar-databricks demo — silver layer. priced_book_input is the "
            "geospatial join sent to WTW Radar (or the simulator notebook). "
            "priced_book_output is what Radar deposits back. radar_run_log "
            "captures audit metadata for each pricing run.",
    gold:   "radar-databricks demo — gold portfolio analytics. flood_concentration "
            "aggregates the priced book by postcode district. scenario_results "
            "pre-computes loss under named flood scenarios (Thames Valley, "
            "Severn, East Coast, Yorkshire, South Coast).",
}

for s, c in SCHEMA_COMMENTS.items():
    try:
        spark.sql(f"COMMENT ON SCHEMA {catalog}.{s} IS '{_esc(c)}'")
        print(f"✓ schema {catalog}.{s}")
    except Exception as e:
        print(f"[err] schema {catalog}.{s}: {str(e)[:120]}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Table comments

# COMMAND ----------

TABLES = {
    f"{catalog}.{bronze}.property_book":
        "Synthetic UK home insurance portfolio — 50,000 policies. Population-"
        "weighted toward UK city centres (London, Manchester, Birmingham, "
        "Leeds, Glasgow, etc.). Source of truth for downstream silver and "
        "gold layers. Generated by 01_bronze/01_generate_property_book.py "
        "with deterministic seed.",

    f"{catalog}.{bronze}.flood_overlay":
        "Synthetic UK postcode-district flood overlay — one row per district "
        "(~150 districts). Flood scores 0–100 with EA-style zone bands "
        "(1, 2, 3a, 3b). Geographically coherent — Thames Valley, Severn, "
        "Trent, Yorkshire (Calder/Aire), East Anglian fens, and south-coast "
        "surge zones all carry elevated risk. No real EA / ABI data used.",

    f"{catalog}.{silver}.priced_book_input":
        "INPUT TO RADAR. Geospatial join of property_book × flood_overlay "
        "with derived columns (flood_factor, risk_band, property_age_band, "
        "exposure_weighted_score). Schema is a contract with the Radar "
        "team — see SCHEMA_HANDOFF.md before changing.",

    f"{catalog}.{silver}.priced_book_output":
        "Output produced by the external pricing system — WTW Radar in "
        "production, simulator notebook (99_radar_simulator) in this demo. "
        "Adds premium, technical_premium, expected_loss, and "
        "loss_ratio_estimate to each row from priced_book_input. Source "
        "for all gold-layer tables.",

    f"{catalog}.{silver}.radar_run_log":
        "Audit trail for Radar simulator runs — one row per pricing run "
        "with row counts, portfolio KPIs, model version, and run "
        "timestamps. In production this is replaced by the Radar job log; "
        "the schema is preserved so downstream dashboards keep working.",

    f"{catalog}.{gold}.flood_concentration":
        "Per-postcode-district concentration view of the priced book — "
        "policy_count, total_exposure, max_single_risk, total_premium, "
        "total_expected_loss, mean_loss_ratio plus the flood overlay "
        "(zone, score, region, watercourse, centroid lat/lng). Primary "
        "table behind the Lakeview map and the top-10 accumulation tile.",

    f"{catalog}.{gold}.scenario_results":
        "Pre-computed loss under named flood scenarios — Thames Valley "
        "1-in-100, Severn Winter Floods, East Coast Surge, Yorkshire "
        "Calder/Aire, South Coast Storm. One row per scenario; severity "
        "multiplier applied to the sum of expected_loss across affected "
        "districts. Drives the dashboard scenario stress tile.",

    f"{catalog}.{gold}.scenario_district_detail":
        "Per-(scenario, district) drill-down for gold.scenario_results. "
        "One row per affected district per scenario.",
}

print(f"Applying comments to {len(TABLES)} tables:")
for fqn, comment in TABLES.items():
    _set_table_comment(fqn, comment)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Column comments — high-traffic tables

# COMMAND ----------

_set_column_comments(f"{catalog}.{bronze}.property_book", {
    "policy_id":          "Unique policy identifier (synthetic, format POL-1000000+)",
    "postcode_district":  "UK postcode district — 1–2 letter area + 1–2 digits (e.g. SW1, M1, BS1). Joins to flood_overlay.postcode_district",
    "sum_insured":        "Total sum insured on the buildings + contents policy (GBP)",
    "property_type":      "Detached / Semi-Detached / Terraced / Flat / Bungalow",
    "build_year":         "Construction year of the primary building",
    "occupancy_type":     "Owner-Occupied / Tenanted / Holiday Let / Vacant",
    "inception_date":     "Policy inception date (uniform over the trailing 12 months)",
})

_set_column_comments(f"{catalog}.{bronze}.flood_overlay", {
    "postcode_district":   "UK postcode district — primary key. Joins to property_book.postcode_district",
    "region":              "ITL1-style UK region label (London, South East, Yorkshire, ...)",
    "flood_zone":          "EA-style flood zone — '1' (low) / '2' (medium) / '3a' (high) / '3b' (functional floodplain)",
    "flood_score":         "Synthetic flood risk score 0–100. 0=lowest, 100=highest",
    "nearest_watercourse": "Name of the nearest meaningful watercourse or coast (NULL if no nearby surface water)",
    "distance_to_water_m": "Approximate distance from district centroid to the named watercourse (metres)",
    "centroid_lat":        "Approximate centroid latitude (WGS84)",
    "centroid_lng":        "Approximate centroid longitude (WGS84)",
})

_set_column_comments(f"{catalog}.{silver}.priced_book_input", {
    "policy_id":               "Unique policy identifier — joins back to bronze.property_book",
    "postcode_district":       "UK postcode district",
    "sum_insured":             "Sum insured (GBP) — passed through from bronze",
    "property_type":           "Building type — passed through from bronze",
    "build_year":              "Construction year — passed through from bronze",
    "occupancy_type":          "Occupancy class — passed through from bronze",
    "inception_date":          "Policy inception — passed through from bronze",
    "region":                  "ITL1-style UK region — joined from flood_overlay",
    "flood_zone":              "EA flood-zone band — joined from flood_overlay",
    "flood_score":             "Flood risk 0–100 — joined from flood_overlay",
    "nearest_watercourse":     "Nearest river / coast name — joined from flood_overlay",
    "distance_to_water_m":     "Distance to nearest watercourse (m)",
    "centroid_lat":            "Postcode-district centroid latitude",
    "centroid_lng":            "Postcode-district centroid longitude",
    "flood_factor":            "Pricing multiplier 1.0–2.5 derived from flood_score (1.0 + flood_score/100 * 1.5)",
    "risk_band":               "Low / Medium / High / Very High — derived from flood_zone",
    "property_age_band":       "Pre-1900 / 1900-1949 / 1950-1979 / 1980-1999 / 2000+ — actuarial age cohort",
    "exposure_weighted_score": "sum_insured × flood_score — used by gold.flood_concentration to compute portfolio-weighted score",
})

_set_column_comments(f"{catalog}.{silver}.priced_book_output", {
    "policy_id":           "Unique policy identifier",
    "postcode_district":   "UK postcode district",
    "sum_insured":         "Sum insured (GBP)",
    "premium":             "Charged annual premium (GBP) — produced by Radar",
    "technical_premium":   "Expected_loss × (1 + expense_loading) — pure technical price excluding margin",
    "expected_loss":       "Burning-cost expected annual loss (GBP) — sum_insured × flood_factor × loss_propensity × property_severity",
    "loss_ratio_estimate": "expected_loss / premium — directional indicator only",
    "flood_factor":        "Pricing multiplier 1.0–2.5 (passed through from input)",
    "risk_band":           "Low / Medium / High / Very High (passed through from input)",
    "_priced_by":          "Identifier of the pricing run (radar_simulator:RUNID in demo, RADAR_RUN_xxx in production)",
})

_set_column_comments(f"{catalog}.{gold}.flood_concentration", {
    "postcode_district":              "UK postcode district — primary key",
    "region":                         "ITL1-style UK region",
    "flood_zone":                     "EA flood-zone band",
    "flood_score":                    "Flood risk 0–100 (district overlay)",
    "nearest_watercourse":            "Nearest river / coast name",
    "centroid_lat":                   "Centroid latitude — used by the Lakeview map",
    "centroid_lng":                   "Centroid longitude — used by the Lakeview map",
    "policy_count":                   "Number of policies in this district",
    "total_exposure":                 "Sum of sum_insured across the district (GBP)",
    "max_single_risk":                "Largest single-policy sum_insured in this district (GBP)",
    "avg_sum_insured":                "Mean sum_insured across the district (GBP)",
    "total_premium":                  "Sum of charged premium across the district (GBP)",
    "total_expected_loss":            "Sum of expected_loss across the district (GBP)",
    "mean_loss_ratio":                "Mean expected_loss / premium across the district",
    "exposure_weighted_flood_score":  "SUM(sum_insured × flood_score) / SUM(sum_insured) — validates choropleth colour",
})

_set_column_comments(f"{catalog}.{gold}.scenario_results", {
    "scenario":              "Named scenario — 'Thames Valley 1-in-100', 'Severn Winter Floods', etc.",
    "narrative":             "Short narrative describing the scenario",
    "severity_multiplier":   "Multiplier applied to base expected_loss for affected districts",
    "affected_districts":    "Array of postcode districts touched by the scenario",
    "districts_count":       "Number of affected districts",
    "policy_count":          "Total policies in affected districts",
    "total_exposure":        "Sum of sum_insured across affected districts (GBP)",
    "total_premium":         "Sum of charged premium across affected districts (GBP)",
    "base_expected_loss":    "Sum of expected_loss across affected districts (GBP) — pre-scenario",
    "scenario_loss":         "base_expected_loss × severity_multiplier (GBP)",
    "loss_to_premium_pct":   "scenario_loss / total_premium × 100 — 'could one event eat the premium we collected from this cluster?'",
})

_set_column_comments(f"{catalog}.{gold}.scenario_district_detail", {
    "scenario":              "Named scenario",
    "postcode_district":     "Affected postcode district",
    "severity_multiplier":   "Severity multiplier for this scenario",
    "policy_count":          "Number of policies in this district",
    "total_exposure":        "Sum of sum_insured (GBP)",
    "base_expected_loss":    "Pre-scenario expected_loss (GBP)",
    "scenario_loss":         "base_expected_loss × severity_multiplier (GBP)",
})

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. UC tags for governance

# COMMAND ----------

COMMON_TAGS = {
    "data_classification": "internal",
    "business_unit":       "pricing",
    "domain":              "property",
    "demo":                "radar-databricks",
}

for fqn in TABLES.keys():
    _set_table_tags(fqn, COMMON_TAGS)

# Extra discriminator on the Radar boundary tables so the schema-handoff
# tables are easy to find in Catalog Explorer.
_set_table_tags(f"{catalog}.{silver}.priced_book_input",  {"radar_boundary": "input"})
_set_table_tags(f"{catalog}.{silver}.priced_book_output", {"radar_boundary": "output"})

# COMMAND ----------

print(f"""
Metadata applied to {catalog}.
  Schemas:  {bronze}, {silver}, {gold}  (comments set)
  Tables:   {len(TABLES)} comments + tags applied (missing tables skipped)

Catalog Explorer at {catalog} will now show descriptions on every
registered object. Re-run any time after a schema change.
""")
